[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nuttaphat", email = "nuttaphat.aruno@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.0",
    "ollama>=0.6.0",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.38.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
